---
- name: Setup enterprise and monitoring
  hosts: all
  become: yes
  vars_files:
    - ./config.yml

  tasks:
    - name: Check if docker installed (CentOS)
      when: ansible_os_family == "RedHat"
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker (CentOS)
      when: ansible_os_family == "RedHat" and docker_installed.failed
      shell: |
        curl -fsSL https://get.docker.com/ | sh

    - name: Install Docker (Ubuntu)
      when: ansible_os_family == "Debian"
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Apache container
      docker_image:
        name: httpd
        source: pull
      when: enterprise_service == 'apache'

    - name: Run Apache container
      docker_container:
        name: apache
        image: httpd
        ports:
          - "80:80"
        state: started
      when: enterprise_service == 'apache'

    - name: Pull Node Exporter container
      docker_image:
        name: prom/node-exporter
        source: pull
      when: monitoring_tool == 'node_exporter'

    - name: Run Node Exporter container
      docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - "9100:9100"
        state: started
      when: monitoring_tool == 'node_exporter'

    - name: Update MOTD
      copy:
        dest: /etc/motd
        content: "Ansible Managed by {{ motd_user | default('Apostol_RuudVan') }}\n"
        owner: root
        group: root
        mode: '0644'
